---
title: Kathryn Wheeler
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: kathrynswheeler@gmail.com
url: https://kathrynwheeler.github.io
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
keywords: your keywords, separated by commas
skills: Producer
meta_author: LastName FirstName
google_verify: 
bing_verify: 
contact: static
disqus_shortname: myshortname
color:
  primary: 9b88ce
  primary-rgb: '155,136,206'
  secondary: 2c3e50
  secondary-dark: 233140
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits
social:
- title: twitter
  url: http://twitter.com/kathrynwheeler
address:
- line: 3481 Melrose Place
- line: Beverly Hills, CA 90210
credits: Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start
  Bootstrap</a>.
markdown: kramdown
permalink: pretty
